zsh: command not found: 0
Traceback (most recent call last):
  File "/Users/jacobford/Documents/GitHub/LinkOfTheDay/link_of_the_day.py", line 58, in <module>
    main()
  File "/Users/jacobford/Documents/GitHub/LinkOfTheDay/link_of_the_day.py", line 43, in main
    data = pd.read_csv(csv_file_path)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'
Email sent to jake.ford927@gmail.com
Traceback (most recent call last):
  File "/Users/jacobford/Documents/GitHub/LinkOfTheDay/link_of_the_day.py", line 58, in <module>
    main()
  File "/Users/jacobford/Documents/GitHub/LinkOfTheDay/link_of_the_day.py", line 48, in main
    scheduled_date = datetime.strptime(row['Date'], "%m/%d/%y")  # Parse the 'Date' column
TypeError: strptime() argument 1 must be str, not float
Email sent to jake.ford927@gmail.com
Traceback (most recent call last):
  File "/Users/jacobford/Documents/GitHub/LinkOfTheDay/link_of_the_day.py", line 58, in <module>
    main()
  File "/Users/jacobford/Documents/GitHub/LinkOfTheDay/link_of_the_day.py", line 48, in main
    scheduled_date = datetime.strptime(row['Date'], "%m/%d/%y")  # Parse the 'Date' column
TypeError: strptime() argument 1 must be str, not float
2025-02-02 11:40:15 - Script started.
2025-02-02 11:40:18 - Email sent to jake.ford927@gmail.com
2025-02-02 11:40:18 - Script completed successfully.
2025-02-02 11:57:21 - Script started.
2025-02-02 11:57:23 - Email sent to jake.ford927@gmail.com
2025-02-02 11:57:23 - Script completed successfully.
